{
 "title": "Azure Stack availability",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Admin endpoint availability", "type": "text", "gridPos": { "h": 1, "w": 8, "x": 0, "y": 0 } },
  { "title": "Tenant endpoint availability", "type": "text", "gridPos": { "h": 1, "w": 16, "x": 8, "y": 0 } },
  {
   "title": "ARM [Admin]",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "admin_arm",
     "query": "SELECT * FROM (SELECT mean(\"job\") FROM \"admin_arm\" WHERE $timeFilter GROUP BY time(1m) fill(0)) OFFSET 1",
     "select": [
      [
       { "params": [ "job" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Admin ARM availability",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 2, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "admin_arm",
     "query": "SELECT * FROM (SELECT mean(\"job\") FROM \"admin_arm\" WHERE $timeFilter GROUP BY time(1m) fill(0)) OFFSET 1",
     "select": [
      [
       { "params": [ "job" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ARM [Tenant]",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "tenant_arm",
     "query": "SELECT * FROM (SELECT mean(\"job\") FROM \"tenant_arm\" WHERE $timeFilter GROUP BY time(1m) fill(0)) OFFSET 1",
     "select": [
      [
       { "params": [ "job" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tenant ARM availability",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "tenant_arm",
     "select": [
      [
       { "params": [ "job" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Storage [Tenant]",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "tenant_storage",
     "query": "SELECT * FROM (SELECT mean(\"job\") FROM \"tenant_storage\" WHERE $timeFilter GROUP BY time(1m) fill(0)) OFFSET 1",
     "select": [
      [
       { "params": [ "job" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tenant Storage availability",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "tenant_storage",
     "query": "SELECT * FROM (SELECT mean(\"job\") FROM \"tenant_storage\" WHERE $timeFilter GROUP BY time(1m) fill(0)) OFFSET 1",
     "select": [
      [
       { "params": [ "job" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Portal [Admin]",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "admin_portal",
     "query": "SELECT * FROM (SELECT mean(\"job\") FROM \"admin_portal\" WHERE $timeFilter GROUP BY time(1m) fill(0)) OFFSET 1",
     "select": [
      [
       { "params": [ "job" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Admin Portal availability",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 2, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "admin_portal",
     "query": "SELECT * FROM (SELECT mean(\"job\") FROM \"admin_portal\" WHERE $timeFilter GROUP BY time(1m) fill(0)) OFFSET 1",
     "select": [
      [
       { "params": [ "job" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Portal [Tenant]",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 4 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "tenant_portal",
     "query": "SELECT * FROM (SELECT mean(\"job\") FROM \"tenant_portal\" WHERE $timeFilter GROUP BY time(1m) fill(0)) OFFSET 1",
     "select": [
      [
       { "params": [ "job" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tenant Portal availability",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 10, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "tenant_portal",
     "query": "SELECT * FROM (SELECT mean(\"job\") FROM \"tenant_portal\" WHERE $timeFilter GROUP BY time(1m) fill(0)) OFFSET 1",
     "select": [
      [
       { "params": [ "job" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PnU states from the last 90 days",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "measurement": "range_pnu",
     "select": [
      [
       { "params": [ "current_version" ], "type": "field" }
      ],
      [
       { "params": [ "new_version" ], "type": "field" }
      ],
      [
       { "params": [ "state" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}