{
 "title": "Azure Stack availability",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "content": "<h2 style=\"text-align:center;color:grey;\">Admin endpoint availability<h2/>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "content": "<h2 style=\"text-align:center;color:grey;\">Tenant endpoint availability<h2/>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "content": "<h2 style=\"text-align:center;color:grey;\">PnU states last 90 days<h2/>"
  },
  {
   "title": "ARM [Admin]",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 2 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "admin_arm",
     "select": [
      [
       { "params": [ "job" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Admin ARM availability",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 2, "y": 2 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "admin_arm",
     "select": [
      [
       { "params": [ "job" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ARM [Tenant]",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 2 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "tenant_arm",
     "select": [
      [
       { "params": [ "job" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tenant ARM availability",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 10, "y": 2 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "tenant_arm",
     "select": [
      [
       { "params": [ "job" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
   "targets": [
    {
     "measurement": "range_pnu",
     "select": [
      [
       { "params": [ "current_version" ], "type": "field" }
      ],
      [
       { "params": [ "new_version" ], "type": "field" }
      ],
      [
       { "params": [ "state" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Portal [Admin]",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 5 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "admin_portal",
     "select": [
      [
       { "params": [ "job" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Admin Portal availability",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 2, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "admin_portal",
     "select": [
      [
       { "params": [ "job" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Portal [Tenant]",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 5 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "tenant_portal",
     "select": [
      [
       { "params": [ "job" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tenant Portal availability",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 10, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "tenant_portal",
     "select": [
      [
       { "params": [ "job" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Storage [Tenant]",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 8 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "tenant_storage",
     "select": [
      [
       { "params": [ "job" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tenant Storage availability",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "tenant_storage",
     "select": [
      [
       { "params": [ "job" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}